# auth-global hooks will be managed / updated across all auth repos.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Lint trailing whitespace
        exclude_types: [image]
      - id: end-of-file-fixer
        name: Lint end-of-file newline
        exclude_types: [image]
      - id: check-added-large-files
        name: Don't permit large files
        exclude_types: [image]

  - repo: local
    hooks:
      - id: cargo-doc
        name: cargo doc
        entry: cargo doc
        language: system
        pass_filenames: false

  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy
      # - id: test

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: JSON and YAML formatting
        types_or: [json, yaml]
