[package]
name = "pgxn_meta"
version = "0.1.0"
description = "The PGXN distribution metadata specification"
repository = "https://github.com/pgxn/pgxn-meta-spec"
authors = ["David E. Wheeler <david@justatheory.com>"]
keywords = ["pgxn", "postgres", "postgresql", "extension", "validation", "distribution"]
license = "PostgreSQL"
categories = ["web-programming", "database"]
edition = "2021"
exclude = [ ".github", ".gitattributes", "target", ".vscode", ".gitignore" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boon = "0.6"
lexopt = "0.3.0"
relative-path = "1.9.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
spdx = "0.10.6"
wax = "0.6.0"

[build-dependencies]
wax = "0.6.0"
serde_json = "1.0"

[dev-dependencies]
