#!/bin/bash

set -e

DESTDIR="${PWD}/target/cover"

rustup component add llvm-tools
cargo install grcov

export RUSTFLAGS="-Cinstrument-coverage"
export LLVM_PROFILE_FILE="${DESTDIR}/default_%m_%p.profraw"
cargo test

grcov "${DESTDIR}" \
    --keep-only 'src/**' \
    --ignore 'src/tests/**' \
    --ignore 'src/**/tests.rs' \
    --excl-line 'unreachable!' \
    --llvm \
    --binary-path "target/debug/" \
    -s . \
    --branch \
    -o "${DESTDIR}" \
    --token 5DOLLPIHEO \
    --output-types html,coveralls,markdown

cat "${DESTDIR}/markdown.md"

if [ "$(uname -o)" = "Darwin" ] && [ -z "$CI" ]; then
	open "${DESTDIR}/html/index.html"
fi
